name: '[Open Intranet] Core Recipe'
description: 'Open Intranet recipe configuration.'
type: 'Open Intranet'
install:
  - address
  - ai
  - ai_ckeditor
  - ai_provider_openai
  - anonymous_redirect
  - automated_cron
  - automatic_updates
  - autosave_form
  - backup_migrate
  - better_exposed_filters
  - block
  - block_content
  - block_visibility_groups
  - book
  - bpmn_io
  - calendar_view
  - calendar_view_multiday
  - ckeditor5
  - ckeditor5_allowed_html
  - ckeditor_iframe
  - ckeditor_media_resize
  - coffee
  - comment
  - claro
  - config
  - config_translation
  - config_perms
  - content_translation
  - contextual
  - crop
  - cshs
  - ctools
  - custom_book_block
  - bootstrap_barrio
  - openintranet_theme
  - dashboard
  - datetime
  - datetime_range
  - datetimehideseconds
  - dblog
  - default_content
  - diff
  - disable_html5_validation
  - dropdown_language
  - dynamic_page_cache
  - editor
  - entity
  - entity_clone
  - entity_clone_extras
  - entity_reference_revisions
  - eca
  - eca_base
  - eca_content
  - eca_modeller_bpmn
  - eca_ui
  - eca_views
  - field
  - field_group
  - field_ui
  - file
  - file_mdm
  - filter
  - flexible_permissions
  - focal_point
  - frontend_editing
  - flag
  - geofield
  - gin
  - gin_toolbar
  - gtm
  - help
  - history
  - iconify_field
  - image
  - imagemagick
  - imce
  - inline_entity_form
  - js_cookie
  - key
  - language
  - layout_builder_styles
  - layout_custom_section_classes
  - leaflet
  - leaflet_markercluster
  - leaflet_views
  - link
  - locale
  - masquerade
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - navigation
  - node
  - noreqnewpass
  - openintranet_messenger
  - openintranet_documents
  - options
  - other_view_filter
  - package_manager
  - page_cache
  - page_manager
  - page_manager_ui
  - paragraphs
  - paragraphs_edit
  - path
  - path_alias
  - openintranet_access
  - openintranet_engagement
  - pathauto
  - pathologic
  - pfdp
  - recently_read
  - recipe_tracker
  - search
  - search_api
  - search_api_db
  - shortcut
  - simple_sitemap
  - smart_trim
  - smsapi
  - sophron
  - statistics
  - system
  - taxonomy
  - update
  - telephone
  - text
  - theme_switcher
  - token
  - toolbar
  - tour
  - twig_tweak
  - twigsuggest
  - user
  - views
  - views_aggregator
  - views_conditional
  - views_organization_chart
  - views_send
  - views_ui
  - votingapi
  - votingapi_reaction
  - project_browser
  - queue_ui
  - webform
  - webform_node
  - webform_ui
config:
  import:
    ai: '*'
    ai_ckeditor: '*'
    anonymous_redirect: '*'
    automated_cron: '*'
    autosave_form: '*'
    backup_migrate: '*'
    block: '*'
    block_content: '*'
    block_visibility_groups: '*'
    book: '*'
    coffee: '*'
    claro: '*'
    comment: '*'
    crop: '*'
    bootstrap_barrio: '*'
    openintranet_theme: '*'
    dashboard: '*'
    dblog: '*'
    dropdown_language: '*'
    editor: '*'
    entity_clone: '*'
    field: '*'
    field_ui: '*'
    file: '*'
    file_mdm: '*'
    filter: '*'
    frontend_editing: '*'
    flag: '*'
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_toolbar: '*'
    image: '*'
    imagemagick: '*'
    imce: '*'
    key: '*'
    language: '*'
    locale: '*'
    masquerade: '*'
    media: '*'
    media_library: '*'
    menu_ui: '*'
    navigation: '*'
    node: '*'
    noreqnewpass: '*'
    openintranet_access: '*'
    openintranet_engagement: '*'
    openintranet_messenger: '*'
    openintranet_documents: '*'
    pathauto: '*'
    pathologic: '*'
    pfdp: '*'
    recently_read: '*'
    search_api: '*'
    search_api_db: '*'
    shortcut: '*'
    simple_sitemap: '*'
    sophron: '*'
    statistics: '*'
    taxonomy: '*'
    text: '*'
    theme_switcher: '*'
    user: '*'
    views: '*'
    votingapi: '*'
    webform: '*'
    webform_node: '*'
    system:
      - system.menu.footer---legal-compliance
      - system.menu.footer---quick-links
      - core.entity_form_display.block_content.banner_block.default.yml
      - core.entity_form_display.block_content.basic.default.yml
      - core.entity_form_display.block_content.links_block.default.yml
      - core.entity_form_display.block_content.quick_action.default.yml
      - core.entity_form_display.comment.comment.default.yml
      - core.entity_form_display.comment.comment_node_article.default.yml
      - core.entity_form_display.comment.comment_node_page.default.yml
      - core.entity_form_display.media.audio.default.yml
      - core.entity_form_display.media.audio.media_library.yml
      - core.entity_form_display.media.document.default.yml
      - core.entity_form_display.media.document.media_library.yml
      - core.entity_form_display.media.image.default.yml
      - core.entity_form_display.media.image.media_library.yml
      - core.entity_form_display.media.remote_video.default.yml
      - core.entity_form_display.media.remote_video.media_library.yml
      - core.entity_form_display.media.video.default.yml
      - core.entity_form_display.media.video.media_library.yml
      - core.entity_form_display.node.article.default.yml
      - core.entity_form_display.node.event.default.yml
      - core.entity_form_display.node.knowledge_base_page.default.yml
      - core.entity_form_display.node.page.default.yml
      - core.entity_form_display.node.webform.default.yml
      - core.entity_form_display.taxonomy_term.office.default.yml
      - core.entity_form_display.user.user.default.yml
      - core.entity_form_mode.media.media_library.yml
      - core.entity_view_display.block_content.banner_block.default.yml
      - core.entity_view_display.block_content.basic.default.yml
      - core.entity_view_display.block_content.links_block.default.yml
      - core.entity_view_display.block_content.quick_action.default.yml
      - core.entity_view_display.comment.comment.default.yml
      - core.entity_view_display.comment.comment_node_article.default.yml
      - core.entity_view_display.comment.comment_node_page.default.yml
      - core.entity_view_display.media.audio.default.yml
      - core.entity_view_display.media.audio.media_library.yml
      - core.entity_view_display.media.document.default.yml
      - core.entity_view_display.media.document.media_library.yml
      - core.entity_view_display.media.image.cke_media_resize_large.yml
      - core.entity_view_display.media.image.cke_media_resize_medium.yml
      - core.entity_view_display.media.image.cke_media_resize_small.yml
      - core.entity_view_display.media.image.cke_media_resize_xl.yml
      - core.entity_view_display.media.image.default.yml
      - core.entity_view_display.media.image.media_library.yml
      - core.entity_view_display.media.remote_video.default.yml
      - core.entity_view_display.media.remote_video.media_library.yml
      - core.entity_view_display.media.video.default.yml
      - core.entity_view_display.media.video.media_library.yml
      - core.entity_view_display.node.article.block_teaser.yml
      - core.entity_view_display.node.article.default.yml
      - core.entity_view_display.node.article.full.yml
      - core.entity_view_display.node.article.grid_layout.yml
      - core.entity_view_display.node.article.rss.yml
      - core.entity_view_display.node.article.search_result.yml
      - core.entity_view_display.node.article.teaser.yml
      - core.entity_view_display.node.event.block_teaser.yml
      - core.entity_view_display.node.event.default.yml
      - core.entity_view_display.node.event.full.yml
      - core.entity_view_display.node.event.teaser.yml
      - core.entity_view_display.node.knowledge_base_page.default.yml
      - core.entity_view_display.node.knowledge_base_page.full.yml
      - core.entity_view_display.node.knowledge_base_page.search_result.yml
      - core.entity_view_display.node.knowledge_base_page.teaser.yml
      - core.entity_view_display.node.page.block_teaser.yml
      - core.entity_view_display.node.page.default.yml
      - core.entity_view_display.node.page.full.yml
      - core.entity_view_display.node.page.grid_layout.yml
      - core.entity_view_display.node.page.search_result.yml
      - core.entity_view_display.node.page.teaser.yml
      - core.entity_view_display.node.webform.default.yml
      - core.entity_view_display.node.webform.teaser.yml
      - core.entity_view_display.taxonomy_term.office.default.yml
      - core.entity_view_display.user.user.compact.yml
      - core.entity_view_display.user.user.default.yml
      - core.entity_view_display.user.user.full_embedded.yml
      - core.entity_view_display.user.user.search_result.yml
      - core.entity_view_display.user.user.user_profile.yml
      - core.entity_view_display.user.user.user_profile_teaser.yml
      - core.entity_view_mode.block.token.yml
      - core.entity_view_mode.block_content.full.yml
      - core.entity_view_mode.block_content.token.yml
      - core.entity_view_mode.comment.full.yml
      - core.entity_view_mode.comment.token.yml
      - core.entity_view_mode.file.token.yml
      - core.entity_view_mode.media.cke_media_resize_large.yml
      - core.entity_view_mode.media.cke_media_resize_medium.yml
      - core.entity_view_mode.media.cke_media_resize_small.yml
      - core.entity_view_mode.media.cke_media_resize_xl.yml
      - core.entity_view_mode.media.full.yml
      - core.entity_view_mode.media.media_library.yml
      - core.entity_view_mode.media.token.yml
      - core.entity_view_mode.menu_link_content.token.yml
      - core.entity_view_mode.node.block_teaser.yml
      - core.entity_view_mode.node.full.yml
      - core.entity_view_mode.node.grid_layout.yml
      - core.entity_view_mode.node.print.yml
      - core.entity_view_mode.node.rss.yml
      - core.entity_view_mode.node.search_result.yml
      - core.entity_view_mode.node.teaser.yml
      - core.entity_view_mode.node.token.yml
      - core.entity_view_mode.paragraph.preview.yml
      - core.entity_view_mode.path_alias.token.yml
      - core.entity_view_mode.taxonomy_term.full.yml
      - core.entity_view_mode.taxonomy_term.token.yml
      - core.entity_view_mode.user.full_embedded.yml
      - core.entity_view_mode.user.search_result.yml
      - core.entity_view_mode.user.token.yml
      - core.entity_view_mode.user.user_profile.yml
      - core.entity_view_mode.user.user_profile_teaser.yml
      - core.entity_view_mode.node.search_result
      - core.entity_view_mode.node.teaser
      - core.entity_view_mode.node.rss
      - core.entity_view_mode.media.media_library
      - core.entity_view_mode.node.block_teaser
      - core.entity_view_mode.user.user_profile

  actions:
    system.site:
      simpleConfigUpdate:
        page:
          front: '/news-homepage'
          403: '/user/login'

    system.theme:
      simpleConfigUpdate:
        admin: gin
        default: openintranet_theme

    system.theme.global:
      simpleConfigUpdate:
        features:
          comment_user_picture: true
          comment_user_verification: true
          favicon: true
          node_user_picture: true

    user.settings:
      simpleConfigUpdate:
        register: 'admin_only'

    votingapi.vote_type.reaction_like:
        simpleConfigUpdate:
          third_party_settings:
            votingapi_reaction:
              reaction: true
              icon_type: remote_image
              icon_class: ''
              uploaded_image: ''
              remote_image: /themes/custom/openintranet_theme/images/icons/thumbs-up.svg
              html_element: ''

    package_manager.settings:
      simpleConfigUpdate:
        additional_trusted_composer_plugins:
          - cweagans/composer-patches
          - oomphinc/composer-installers-extender
          - wikimedia/composer-merge-plugin
          - zaporylie/composer-drupal-optimizations
    project_browser.admin_settings:
      simpleConfigUpdate:
        default_source: recipes
        enabled_sources:
          recipes: {}
        allow_ui_install: true
        max_selections: 1
    user.role.authenticated:
      simpleConfigUpdate:
        dependencies:
          config:
            - filter.format.webform_default
          module:
            - comment
            - filter
            - flag
            - media
            - openintranet_documents
            - openintranet_engagement
            - pfdp
            - system
            - votingapi_reaction
        permissions:
          - 'access comments'
          - 'access content'
          - 'access user profiles'
          - 'bypass pfdp'
          - 'bypass pfdp for temporary files'
          - 'create reaction on node:article:field_news_article_reaction'
          - 'create reaction on node:page:field_basic_page_reaction'
          - 'download oi_document'
          - 'edit own comments'
          - 'flag read'
          - 'unflag read'
          - 'flag bookmark'
          - 'unflag bookmark'
          - 'modify reaction on node:article:field_news_article_reaction'
          - 'modify reaction on node:page:field_basic_page_reaction'
          - 'post comments'
          - 'skip comment approval'
          - 'use text format webform_default'
          - 'view media'
          - 'view oi_document'
          - 'view own engagement score'
          - 'view oi_folder'
          - 'view reactions on node:article:field_news_article_reaction'
          - 'view reactions on node:page:field_basic_page_reaction'
