#!/usr/bin/env bash

THEME_DIR="/var/www/html/web/themes/custom/openintranet_theme"

# Install openintranet_theme npm packages.
cd  ${THEME_DIR}
npm install

# Check if user wants instant-update.
if [ "$1" == "compile" ]; then
  echo "Compiling styles, minified version."
  gulp
fi
